### ISSUE TITLE
Image not showing in README.md

### ISSUE THREAD

**Issue by saurabhhere** [Cheatsheet-lang/HTML#11]
![Screenshot from 2020-10-07 19-58-27](https://user-images.githubusercontent.com/60233336/95353826-5adc8f80-08e1-11eb-9b26-d0bccbe5abbf.png)

**Comment by saurabhhere** [comment]
#12 
@AnuragAnalog  Have a look on this.

**Comment by AnuragAnalog** [comment]
Merged your request!
